### ISSUE TITLE
running "node index.js " encounter error

### ISSUE THREAD

**Issue by luckypoem** [javimosch/ssgenv#1]
hi.
git clone https://github.com/javimosch/staticstuff
cd staticstuff
npm install
node index.js

shows:
root@AR:~/staticstuff-site# node index.js
he config prod false
loading config myprojectname
APP rich
/root/staticstuff-site/lib/he.js:95
    appData.app = appName;
                ^

TypeError: Cannot set property 'app' of undefined
    at Object.setApp (/root/staticstuff-site/lib/he.js:95:17)
    at Object.<anonymous> (/root/staticstuff-site/index.js:19:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
root@AR:~/staticstuff-site#

how to fix it?

**Comment by javimosch** [comment]
Hi
Sorry, there is a lot of undocumented proccess.
Right now you use ./dev.sh [NAME_OF_YOUR_PROJECT] to run dev enviroment.
The same for ./watch.sh  (same as dev.sh but do not start local server)
The same for ./build.sh (compile to dist-production)

**Comment by luckypoem** [comment]
hi.

still same error:

oot@AR:/usr/local/staticstuff-site# ./dev.sh site
[1] loading config myprojectname
[1] static-content - src - routing /myprojectname/src
[1] static-content - vendor - routing /myprojectname/vendor
[1] static-content - Production? Non!
[1] static-content - serverURL http://localhost:5000
[1] static-content - listening on port 8082!
[0] he config prod false
[0] loading config myprojectname
[0] APP site
[0] /usr/local/staticstuff-site/lib/he.js:95
[0]     appData.app = appName;
[0]                 ^
[0] 
[0] TypeError: Cannot set property 'app' of undefined
[0]     at Object.setApp (/usr/local/staticstuff-site/lib/he.js:95:17)
[0]     at Object.<anonymous> (/usr/local/staticstuff-site/index.js:19:11)
[0]     at Module._compile (module.js:398:26)
[0]     at Object.Module._extensions..js (module.js:405:10)
[0]     at Module.load (module.js:344:32)
[0]     at Function.Module._load (module.js:301:12)
[0]     at Function.Module.runMain (module.js:430:10)
[0]     at startup (node.js:141:18)
[0]     at node.js:980:3
[0] node index.js exited with code 1
--> Sending SIGTERM to other processes..
[1] node server.js exited with code null
root@AR:/usr/local/staticstuff-site#

how to fix it?

**Comment by javimosch** [comment]
Hi luckypoem,
So sorry you did not get this working. I really need help to document this project.
I pushed a commit with example project so you can get an idea about how the things works.

brief explanation:

staticstuff watch and compilation is divided by directories (you can call them projects or isolated parts of your main project). 
To create a project or isolated directory to start working you need to create several folders and a config file as follow:

example name "site"
root/config/config-site.js
root/src/css/site
root/src/js/site
root/src/partial/stie
root/src/static/site

Take a look at the  files inside myprojectname and try to replicate your own.
If the directories and the config file exist you should then start developing with
./dev.sh site
public url of your scope will be http://youripaddress:port/[name]

note: .env to change port
